development:
    dialect: postgres
    datasource: dbname=strong sslmode=disable
    dir: migrations/postgres

production:
    dialect: postgres
    datasource: dbname=<%= ENV['DB_NAME'] %> user=<%= ENV['DB_USER'] %> password=<%= ENV['DB_PASSWORD'] %> sslmode=<%= ENV['DB_SSL_MODE'] %>
    dir: migrations/postgres
